# Generated by Django 5.2.17 on 2026-09-11 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_available_product_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank if stock is not tracked. Zero means sold out. For products with options, edit stock on each variant.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Blank = not tracked; 0 = sold out.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Existing static image path. An uploaded photo takes precedence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='source_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
