from django.db import migrations

PAGES = [
('refund-policy', 'Refund Policy', 'Help with refunds and returns.', True,
 'Refund arrangements are being finalized\nASTROL has not yet published a return window, eligibility conditions, return address or refund processing time. Online checkout is not currently available.\n\nBefore making a purchase\nConfirm the terms for the exact product, including any exclusions for customised or worn items. Do not send a return until the ASTROL team provides instructions.\n\nAsk for help\nUse Contact Us with the product name and, if you have one, your order reference. Please do not include payment passwords or full card details.'),
('shipping-policy', 'Shipping Policy', 'Delivery information for your spiritual essentials.', True,
 'Delivery arrangements\nDispatch times, courier services, shipping charges and supported destinations are being finalized. Delivery dates are not currently quoted by this storefront.\n\nCountry and currency\nThe country selector changes displayed currency estimates. It does not confirm delivery availability, import charges or local taxes for that destination.\n\nBefore ordering\nContact ASTROL to confirm service to your postal code and any delivery charges. Tracking information will depend on the shipping service arranged for a confirmed order.'),
('cancellation-policy', 'Cancellation Policy', 'Guidance on changing your selection.', True,
 'Before an order is placed\nYou can remove products from your shopping cart at any time. Adding a product to the cart does not place an order or reserve stock.\n\nCancellation arrangements\nOnline checkout is not yet available. Cancellation deadlines and any rules for customised or dispatched products are being finalized.\n\nNeed assistance?\nFor a purchase arranged directly with ASTROL, contact the team with your reference and requested change. Cancellation availability must be confirmed for that purchase.'),
('terms-of-services', 'Terms of Service', 'Using the ASTROL storefront.', True,
 'About this storefront\nYou can browse products, save a wishlist, manage your account and prepare a shopping cart. Payment collection and online order placement are not yet available. Final purchase terms are being prepared.\n\nProduct information\nNatural materials can vary in appearance. Check the listed option, dimensions and price for your selection. Sample listings use illustrative images and prices and are not available for purchase.\n\nCurrency estimates\nInternational prices use cached exchange rates. The displayed date identifies the rate snapshot. Shipping, duties and taxes are not included in these estimates.\n\nTraditional context\nSpiritual associations describe beliefs and traditions. They do not guarantee health, financial or other personal outcomes.\n\nYour account\nKeep your password private and use accurate details when contacting us. Please use the site respectfully and do not submit information belonging to another person without their permission.'),
('privacy-policy', 'Privacy Policy', 'How information is used in the current ASTROL storefront.', True,
 'Information you provide\nWhen you create an account, the site stores your username, email and profile details. Saved addresses and wishlist items are linked to your account. Passwords are stored in a protected form, not as readable text.\n\nEnquiries and subscriptions\nContact forms store your name, email, subject and message for the ASTROL team to review. Newsletter signup stores your email, signup time and subscription status when you choose to subscribe. Signing up does not create a customer account.\n\nCookies and browser storage\nCookies support sessions, security and your country preference. Guest wishlists may be stored in your browser. Clearing browser data can remove these preferences.\n\nAccess and corrections\nYou can edit account information and addresses in My Account. To request other corrections, deletion or removal from the newsletter list, use Contact Us.\n\nDetails being finalized\nThe business contact details and formal retention arrangements are still to be supplied. This page describes the current storefront and will need updating as payment, delivery and email services are introduced.'),
('faqs', 'FAQs', 'A little guidance for your ASTROL journey.', False,
 'How do I find a product?\nUse Search or browse a collection. On All Products, combine category, origin, Mukhi, price and availability filters, then choose your preferred sorting order.\n\nHow do I change the currency?\nOpen Change country / currency above the ASTROL logo. Choose your country and select Update prices. International prices are estimates using the displayed rate date.\n\nHow do product options work?\nOpen a product page and select an available size or finish. The price updates for that option. Sold-out options cannot be added to the cart.\n\nWhat is a sample product?\nSamples illustrate future collection styles. Their images and prices are examples, and samples cannot be purchased.\n\nCan I save favourites?\nUse the heart on a product. Signed-in customers can find saved products in their account wishlist; guest selections stay in the current browser.\n\nCan I place an order now?\nYou can prepare a cart, but online checkout and payment are not yet connected. Contact ASTROL for product enquiries.\n\nWhere can I find delivery and return information?\nSee Shipping Policy and Refund Policy. The business terms are being finalized, so confirm them with ASTROL before arranging a purchase.\n\nHow should I care for my product?\nRead the Care guidance on its product page. Care varies with the material, treatment and fastening.\n\nHow can I get help?\nUse Contact Us to save an enquiry for the team. Include the product name or reference so your question is clear.'),
]

def seed(apps, schema_editor):
    Page = apps.get_model('store', 'InformationPage')
    for slug, title, intro, pending, body in PAGES:
        Page.objects.get_or_create(slug=slug, defaults={'title': title, 'intro': intro, 'needs_confirmation': pending, 'body': body})
    apps.get_model('store', 'StoreContact').objects.get_or_create(pk=1)

class Migration(migrations.Migration):
    dependencies = [('store', '0005_informationpage_newslettersubscriber_storecontact_and_more')]
    operations = [migrations.RunPython(seed, migrations.RunPython.noop)]
