# Generated by Django 5.2.17 on 2026-09-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_seed_help_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecontact',
            name='secondary_phone_number',
            field=models.CharField(blank=True, help_text='Additional contact number, including country code; digits only.', max_length=20),
        ),
    ]
